Administration.Site/Models/Student/StudentAddModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Web.Mvc;
using ModuleChooser.Resources.Strings;

namespace Administration.Site.Models
{
    public class StudentAddModel
    {
        [DisplayName("First Name")]
        [Required]
        public string FirstName { get; set; }
        
        [Required]
        public string Surname { get; set; }
       

        [DisplayName("Course")]
        [Required]
        public string Course { get; set; }

        public List<SelectListItem> CourseOptions = 
            new List<SelectListItem>
            {
                new SelectListItem
                {
                    Text = "Select the course",
                    Disabled = true,
                    Selected = true,
                    Value = "0",

                }
            };

        [DisplayName("Username")]
        public string Username { get; set; }
    }
}

Administration.Site/Models/Student/StudentEditModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Web.Mvc;
using ModuleChooser.Resources.Strings;

namespace Administration.Site.Models
{
    public class StudentEditModel
    {
        public Guid StudentId { get; set; }

        [DisplayName("First Name")]
        [Required]
        public string FirstName { get; set; }
        
        [Required]
        public string Surname { get; set; }

        [DisplayName("Year of Study")]
        [Required(ErrorMessageResourceName = "YearOfStudyRequired", ErrorMessageResourceType = typeof(Strings))]
        public int YearOfStudy { get; set; }

        public IEnumerable<SelectListItem> YearOptions =
            new List<SelectListItem>
            {
                new SelectListItem
                {
                    Text = "Select your option",
                    Disabled = true,
                    Selected = true,
                    Value = "0",

                },
                new SelectListItem
                {
                    Text = "1",
                    Disabled = false,
                    Selected = false,
                    Value = "1",

                },
                new SelectListItem
                {
                    Text = "2",
                    Disabled = false,
                    Selected = false,
                    Value = "2"
                },
                new SelectListItem
                {
                    Text = "3",
                    Disabled = false,
                    Selected = false,
                    Value = "3"
                },
                new SelectListItem
                {
                    Text = "4",
                    Disabled = false,
                    Selected = false,
                    Value = "4"
                },
                new SelectListItem
                {
                    Text = "5",
                    Disabled = false,
                    Selected = false,
                    Value = "5"
                },
            };

        [DisplayName("Course")]
        [Required]
        public String Course { get; set; }

        public List<SelectListItem> CourseOptions = 
            new List<SelectListItem>
            {
                new SelectListItem
                {
                    Text = "Select the course",
                    Disabled = true,
                    Selected = true,
                    Value = "0",

                }
            };        
    }
}

Administration.Site/Models/Student/StudentModel.cs
using System;

namespace Administration.Site.Models
{
    public class StudentModel
    {
        public Guid StudentId { get; set; }

        public string FullName { get; set; }

        public int YearOfStudy { get; set; }

        public Guid CourseId { get; set; }

        public string CourseTitle { get; set; }
    }
}

Administration.Site/Controllers/StudentController.cs
using AutoMapper;
using Administration.Site.Models;
using System.Collections.Generic;
using System.Threading.Tasks;
using System.Web.Mvc;
using System;
using ModuleChooser.Resources;
using Administration.Service;
using SignOn.Helpers;

namespace Administration.Site.Controllers
{
    //The user must have the role of an administrator to view the site.
    [ModuleChooserAuthorize(Roles = "Admin")]
    public class StudentController : Controller
    {
        //Initialise the service to get data and the mapper used to map classes of one type to another
        private readonly IAdministrationService _service;
        private readonly IMapper _mapper;

        //Service and mappers injected to controller and values are assigned to the variables
        public StudentController(IAdministrationService service, IMapper mapper)
        {
            _service = service;
            _mapper = mapper;
        }

        public async Task<ViewResult> StudentList()
        {
            //Get all of the students
            var dtos = await _service.GetStudents();

            //Map the dto information to the model to be used by the view.
            var model = _mapper.Map<List<StudentModel>>(dtos);

            //Pass the model to the view and render StudentList page
            return View("StudentList", model);
        }

        public async Task<ActionResult> EditStudent(Guid studentId)
        {
            //Create new edit student model
            var model = new StudentEditModel();

            //Get all the courses
            var courses = await _service.GetCourses();

            //Get all of the informatiion needed to edit a student
            var studentInfoDto = await _service.GetStudentEditInformation(studentId);

            //Assign the student dto information to the model
            model.FirstName = studentInfoDto.FirstName;
            model.Surname = studentInfoDto.Surname;
            model.StudentId = studentId;
            model.YearOfStudy = studentInfoDto.YearOfStudy;
            
            //For each course, add an option to the select list. Assign the default selected value to the course the student is currently on.
            foreach(var course in courses)
            {
                model.CourseOptions.Add(new SelectListItem
                {
                    Text = course.Title,
                    Disabled = false,
                    Selected = studentInfoDto.CourseId == course.Id,
                    Value = course.Id.ToString(),
                });
            }

            //Render the edit student view, passing through the model
            return View(model);
        }

        public async Task<ActionResult> AddStudent()
        {
            //Create a new Add Student Model
            var model = new StudentAddModel();

            //Get all of the courses
            var courses = await _service.GetCourses();

            //For each course, add it as an option in the select list 
            foreach (var course in courses)
            {
                model.CourseOptions.Add(new SelectListItem
                {
                    Text = course.Title,
                    Disabled = false,
                    Value = course.Id.ToString(),
                });
            }

            //Render the AddStudent View, passing through the model
            return View(model);
        }

        public async Task<ActionResult> SaveExistingStudent(StudentEditModel model)
        {
            //Check that the form information is valid. If not return back to the view.
            if (!ModelState.IsValid)
            {
                //Get all of the courses
                var courses = await _service.GetCourses();

                //For each course, add it as an option in the select list 
                foreach (var course in courses)
                {
                    model.CourseOptions.Add(new SelectListItem
                    {
                        Text = course.Title,
                        Disabled = false,
                        Value = course.Id.ToString(),
                    });
                }

                return View("EditStudent", model);
            }

            //Create a new dto with the model information assigned, to be passed to the save method
            var dto = new SaveStudentDto()
            {
                CourseId = Guid.Parse(model.Course),
                FirstName = model.FirstName,
                YearOfStudy = model.YearOfStudy,
                StudentId = model.StudentId,
                Surname = model.Surname
            };

            //Save the existing student information
            await _service.SaveExistingStudent(dto);

            //Redirect to the student list action.
            return RedirectToAction("StudentList");
        }

        public async Task<ActionResult> AddNewStudent(StudentAddModel model)
        {
            //Check that the form information is valid. If not return back to the view.
            if (!ModelState.IsValid)
            {
                //Get all of the courses
                var courses = await _service.GetCourses();

                //For each course, add it as an option in the select list 
                foreach (var course in courses)
                {
                    model.CourseOptions.Add(new SelectListItem
                    {
                        Text = course.Title,
                        Disabled = false,
                        Value = course.Id.ToString(),
                    });
                }

                return View("AddStudent", model);
            }

            //Create a new dto with the model information assigned, to be passed to the save method
            var dto = new SaveStudentDto()
            {
                CourseId = Guid.Parse(model.Course),
                FirstName = model.FirstName,
                YearOfStudy = 1,
                Surname = model.Surname,   
                Username = model.Username
            };

            //Save the new student information
            await _service.SaveNewStudent(dto);

            //Redirect to the student list action.
            return RedirectToAction("StudentList");
        }
    }
}

Administration.Site/Views/Student/AddStudent.cshtml
@using Administration.Site.Models;
@using ModuleChooser.Resources.Strings;

@{
    ViewBag.Title = Strings.AddStudent;
}

@section RenderCss {
    <link rel="stylesheet" href="~/Content/AddModule.css" type="text/css" />
}

@model StudentAddModel

<h2>@Strings.AddStudent</h2>

<form id="form" action="@Url.Action("AddNewStudent", "Student")" method="post">
    <div id="information-div">
        <h3>@Strings.StudentInformation:</h3>
        <hr />
        <div>
            @Html.LabelFor(m => m.FirstName, new { @class = "information-label" })
            @Html.TextBoxFor(m => m.FirstName)
            @Html.ValidationMessageFor(m => m.FirstName)
        </div>
        <div>
            @Html.LabelFor(m => m.Surname, new { @class = "information-label" })
            @Html.TextBoxFor(m => m.Surname)
            @Html.ValidationMessageFor(m => m.Surname)
        </div>
        <div>
            @Html.LabelFor(m => m.Course, new { @class = "information-label" })
            @Html.DropDownListFor(m => m.Course, Model.CourseOptions)
            @Html.ValidationMessageFor(m => m.Course)
        </div>
        <div>
            @Html.LabelFor(m => m.Username, new { @class = "information-label" })
            @Html.TextBoxFor(m => m.Username)
            @Html.ValidationMessageFor(m => m.Username)
        </div>
    </div>
    <div>
        <input class="button" type="submit" value="Save" />
    </div>
</form>

Administration.Site/Views/Student/EditStudent.cshtml
@using Administration.Site.Models;
@using ModuleChooser.Resources.Strings;

@{
    ViewBag.Title = Strings.EditStudent;
}
@section RenderCss {
    <link rel="stylesheet" href="~/Content/AddModule.css" type="text/css" />
}
@model StudentEditModel

<h2>@Strings.EditStudent</h2>

<form id="form" action="@Url.Action("SaveExistingStudent", "Student")" method="post">
    @Html.HiddenFor(m => m.StudentId)
    <div id="information-div">
        <h3>@Strings.StudentInformation:</h3>
        <hr />
        <div>
            @Html.LabelFor(m => m.FirstName, new { @class = "information-label" })
            @Html.TextBoxFor(m => m.FirstName)
            @Html.ValidationMessageFor(m => m.FirstName)
        </div>
        <div>
            @Html.LabelFor(m => m.Surname, new { @class = "information-label" })
            @Html.TextBoxFor(m => m.Surname)
            @Html.ValidationMessageFor(m => m.Surname)
        </div>
        <div>
            @Html.LabelFor(m => m.Course, new { @class = "information-label" })
            @Html.DropDownListFor(m => m.Course, Model.CourseOptions)
            @Html.ValidationMessageFor(m => m.Course)
        </div>
        <div>
            @Html.LabelFor(m => m.YearOfStudy, new { @class = "information-label" })
            @Html.DropDownListFor(m => m.YearOfStudy, Model.YearOptions)
            @Html.ValidationMessageFor(m => m.YearOfStudy)
        </div>
    </div>
    <div>
        <input class="button" type="submit" value="Save" />
    </div>
</form>

Administration.Site/Views/Student/StudentList.cshtml
@using Administration.Site.Models
@using ModuleChooser.Resources.Strings;

@{
    ViewBag.Title = Strings.StudentList;
    ViewBag.Heading = Strings.StudentList;
}

@model List<StudentModel>

<table id="table_id" class="table table-condensed table-striped table-hover">
    <thead>
        <tr>
            <th>
                @Strings.Name
            </th>
            <th>
                @Strings.Course
            </th>
            <th>
               @Strings.YearOfStudy
            </th>
            <th>
            </th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.FullName)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.CourseTitle)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.YearOfStudy)
                </td>
                <td>
                    @Html.ActionLink(Strings.EditStudent, "EditStudent",
                         new { studentId = item.StudentId }, htmlAttributes: new
                         {
                             @class = "btn btn-default btn-sm add-modules-button"
                         })
                </td>
            </tr>
        }
    </tbody>
</table>