PotentialStudent.Site/Models/CourseCompactModel.cs
using System;

namespace PotentialStudent.Site.Models
{
    public class CourseCompactModel
    {
        public Guid Id { get; set; }

        public string Title { get; set; }
    }
}

PotentialStudent.Site/Models/ModuleListModel.cs
using ModuleChooser.Resources.Dtos;
using System.Collections.Generic;

namespace PotentialStudent.Site.Models
{
    public class ModuleListModel : ModuleModel
    {
        public bool Compulsory { get; set; }

        public List<PrerequisitesForModuleDto> ModulePrerequisites { get; set; }

        public List<FutureAvailableOptionsFromModuleDto> FutureAvailableOptions { get; set; }

        public bool AbleToBeChosen { get; set; }
    }
}

PotentialStudent.Site/Models/ModuleModel.cs
using System;

namespace PotentialStudent.Site.Models
{
    public class ModuleModel
    {
        public string ModuleCode { get; set; }

        public string Title { get; set; }

        public string Semester { get; set; }

        public int Credits { get; set; }

        public int YearOfStudy { get; set; }

        public Guid ModuleId { get; set; }

        public string Url { get; set; }
    }
}

PotentialStudent.Site/Controllers/ModuleController.cs
using AutoMapper;
using PotentialStudent.Service;
using PotentialStudent.Site.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.Web.Mvc;

namespace PotentialStudent.Site.Controllers
{
    public class ModuleController : Controller
    {
        //Initialise the service to get data and the mapper used to map classes of one type to another
        private readonly IPotentialStudentService _service;
        private readonly IMapper _mapper;

        //Service and mappers injected to controller and values are assigned to the variables
        public ModuleController(IPotentialStudentService service, IMapper mapper)
        {
            _service = service;
            _mapper = mapper;
        }

        public async Task<ViewResult> ModuleList()
        {
            //Get the courses from the database as a list of dtos.
            var courses = await _service.GetCourses();

            //Map the dto to the compact course model list to be used by the view
            var model = _mapper.Map<List<CourseCompactModel>>(courses);

            //Render the modulelist view, passing through the model
            return View(model);
        }

        public async Task<ViewResult> ModuleListPartial(Guid courseId)
        {
            //Get the modules from the database for the course as a dto list.
            var dtos = await _service.GetModulesForCourse(courseId);

            //Order the modules by compulsory ones, then by year of study and then by their semester
            dtos = dtos.OrderBy(m => m.Compulsory)
                    .ThenBy(m => m.YearOfStudy).ThenBy(m => m.Semester).ToList();

            //Get all of the compulsory modules
            var compulsoryModules = dtos.Where(m => m.Compulsory).Select(m => m.ModuleId);

            //Don't include compulsory modules in the foreach as they aren't relevant for this sections
            foreach (var module in dtos.Where(m => !m.Compulsory))
            {
                //Get the module prereqs. Order these by year and semester
                module.ModulePrerequisites = _service.GetPrerequisitesForModule(module.ModuleId)
                    .OrderBy(p => p.PrerequisiteYearOfStudy).ThenBy(p => p.PrerequisiteSemester).ToList();

                //Iterate over the module prereqs
                foreach (var mp in module.ModulePrerequisites)
                {
                    //Set the prereq as a compulsory prerequisite if it is one
                    if (compulsoryModules.Contains(mp.PrerequisiteModuleId))
                    {
                        mp.PrerequisiteCompulsory = true;
                    }
                }

                //If all of the module prerequisites are compulsory then make that module able to be chosen
                if (module.ModulePrerequisites.All(mp => mp.PrerequisiteCompulsory))
                {
                    module.AbleToBeChosen = true;
                }

                //Get all of the options that are enabled if this module is chosen and order by the year and semester
                module.FutureAvailableOptions = _service.GetFutureAvailableOptionsForModule(module.ModuleId)
                    .OrderBy(fao => fao.FutureAvailableYearOfStudy).ThenBy(fao => fao.FutureAvailableSemester).ToList();
            }

            //Map the dto list to the ModuleListModel list. This is later used by the view to render data on screen
            var model = _mapper.Map<List<ModuleListModel>>(dtos);

            //Render the modulelist partial view, passing through the model
            return View("_ModuleListPartial", model);
        }
    }
}

PotentialStudent.Site/Views/Module/ModuleList.cshtml
@using PotentialStudent.Site.Models
@using ModuleChooser.Resources.Strings;

@{
    ViewBag.Title = Strings.ModuleList;
    ViewBag.ShowLogo = true;
}

@model List<CourseCompactModel>

@section RenderCss {
    <link rel="stylesheet" href="~/Content/ModuleList.css" type="text/css" />
}

<form action="https://localhost:24080/SignOn/Account/Login">
    <input type="submit" id="sign-in-button" value="@Strings.SignIn" />
</form>
<br />

<div id="loader-div">
    <i class="loader fa fa-spinner fa-spin"></i>
</div>

@Html.Label("Courses", new { @id = "course-label" })
<p>@Strings.CurrentlyNotSignedIn</p>
@Html.DropDownList("Courses", new SelectList(Model, "Id", "Title"))
<input id="view-modules-button" value="View Modules" type="button" onclick="getModuleList()" />
<hr />
<div id="module-list">
</div>

<script>
    function getModuleList() {
        $("select").attr('disabled', 'true');
        //Start loading data
        showLoader()
        //Get course value to use
        var selectedCourseValue = $("#Courses").val();

        //Send GET request to ModuleListPartial, sending the selectedCourseValue and then render the HTML response in the module-list div
        $.ajax({
            url: "@Url.Action("ModuleListPartial", "Module")",
            type: "GET",
            data: {
                courseId: selectedCourseValue
            },
            success: function (response) {
                $("#module-list").html(response);

                //Hide loader.
                $("#loader-div").hide();
                $("input[type=checkbox]").removeAttr('disabled');
                $("select").removeAttr('disabled');
            }
        });
    }

    function showLoader() {
        //Show loader when contents loading
        $("#loader-div").show();
        $("input[type=checkbox]").attr('disabled', 'true');
    }
</script>

PotentialStudent.Site/Views/Shared/_Layout.cshtml
@using ModuleChooser.Resources.Strings;

<!DOCTYPE html>
<html>
<head>
    <link rel="shortcut icon" type="image/x-icon" href="~/icon.ico" />
    <link rel="stylesheet" href="https://cdn.datatables.net/1.10.4/css/jquery.dataTables.min.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - @Strings.University</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    @RenderSection("RenderCss", false)
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    <script src="https://cdn.datatables.net/1.10.4/js/jquery.dataTables.min.js"></script>
</head>
<body>
    <div class="container">
        @if (ViewBag.ShowLogo)
        {
            <text>
                <div class="img-div">
                    <img alt="univeristy of leeds logo" id="uni-logo" src="~/Content/UniversityLogo.png"/>
                </div>
            </text>
        }
        <div id="header-div">
            <h2 id="header">@ViewBag.Heading</h2>
        </div>
        @RenderBody()
    </div>
    @if (ViewBag.ShowLogo)
    {
        <footer>
            <p id="copyright-logo">&copy; @DateTime.Now.Year - Callum Goodridge</p>
        </footer>
    }
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>