Administration.Site/Models/Course/AddCourseModel.cs
using ModuleChooser.Resources.Strings;
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Web.Mvc;

namespace Administration.Site.Models
{
    public class AddCourseModel
    {
        [Required]
        public String Title { get; set; }

        [DisplayName("Length of Course (years)")]
        [Required(ErrorMessageResourceName = "YearOfStudyRequired", ErrorMessageResourceType = typeof(Strings)), Range(1, 5)]
        public int NumberOfYears { get; set; }

        public IEnumerable<SelectListItem> YearOptions =
            new List<SelectListItem>
            {
                new SelectListItem
                {
                    Text = "Select your option",
                    Disabled = true,
                    Selected = true,
                    Value = "0",

                },
                new SelectListItem
                {
                    Text = "1",
                    Disabled = false,
                    Selected = false,
                    Value = "1",

                },
                new SelectListItem
                {
                    Text = "2",
                    Disabled = false,
                    Selected = false,
                    Value = "2"
                },
                new SelectListItem
                {
                    Text = "3",
                    Disabled = false,
                    Selected = false,
                    Value = "3"
                },
                new SelectListItem
                {
                    Text = "4",
                    Disabled = false,
                    Selected = false,
                    Value = "4"
                },
                new SelectListItem
                {
                    Text = "5",
                    Disabled = false,
                    Selected = false,
                    Value = "5"
                },
            };
    }
}

Administration.Site/Models/Course/CourseModel.cs
using System;

namespace Administration.Site.Models
{
    public class CourseModel
    {
        public Guid Id { get; set; }

        public String Title { get; set; }
    }
}

Administration.Site/Controllers/CourseController.cs
using AutoMapper;
using Administration.Site.Models;
using System.Collections.Generic;
using System.Threading.Tasks;
using System.Web.Mvc;
using System;
using ModuleChooser.Resources;
using Administration.Service;
using System.Linq;
using SignOn.Helpers;

namespace Administration.Site.Controllers
{
    //The user must have the role of an administrator to view the site.
    [ModuleChooserAuthorize(Roles = "Admin")]
    public class CourseController : Controller
    {
        //Initialise the service to get data and the mapper used to map classes of one type to another
        private readonly IAdministrationService _service;
        private readonly IMapper _mapper;

        //Service and mappers injected to controller and values are assigned to the variables
        public CourseController(IAdministrationService service, IMapper mapper)
        {
            _service = service;
            _mapper = mapper;
        }

        public async Task<ViewResult> CourseList()
        {
            //Get the courses from the database
            var dtos = await _service.GetCourses();

            //Map the courses dto to the course model list to be used by the CourseList view
            var model = _mapper.Map<List<CourseModel>>(dtos);

            //Render the CourseList view
            return View("CourseList", model);
        }

        public async Task<ViewResult> AddModulesToCourse(Guid courseId)
        {
            //Get the modules which are available for a course
            var courseModules = await _service.GetModulesForCourse(courseId);

            //Get information on all modules
            var dtos = await _service.GetModules();

            //Map the module information dtos to the model
            var model = _mapper.Map<List<AddModulesToCourseModel>>(dtos);

            //for each module do the following
            foreach(var item in model)
            {
                //Check if the module is already assigned to the course
                var courseModule = courseModules.FirstOrDefault(cm => cm.ModuleId == item.ModuleId);

                //if the module is already assigned to the course then set the compulsory and option value.
                //Otherwise do nothing
                if (courseModule != null)
                {
                    item.Compulsory = courseModule.Compulsory;
                    item.Option = !courseModule.Compulsory;
                }
            }            

            //Set the course id to be used by the view
            ViewBag.CourseId = courseId;

            //Render the AddModulesToCourse view along with the view model.
            return View("AddModulesToCourse", model);
        }
        
        public async Task SaveModuleToCourse(Guid moduleId, Guid courseId, bool compulsory)
        {
            //Using the moduleid, courseid and whether the module is compulsory or not, save the module to the course
            await _service.SaveModuleToCourse(moduleId, courseId, compulsory);
        }

        public async Task RemoveModuleFromCourse(Guid moduleId, Guid courseId)
        {
            //Using the moduleid, and courseid, remove the module from the course
            await _service.RemoveModuleFromCourse(moduleId, courseId);
        }

        public async Task ChangeCompulsoryStatus(Guid moduleId, Guid courseId)
        {
            //Using the moduleid, and courseid, change the compulsory status of the course
            await _service.ChangeCompulsoryStatus(moduleId, courseId);
        }

        public ViewResult AddCourse()
        {
            //Render the AddCourse view passing through the model
            var model = new AddCourseModel();
            return View(model);
        }

        public async Task<ActionResult> SaveNewCourse(AddCourseModel model)
        {
            //Check if the form data is correct, if not return to the view
            if (!ModelState.IsValid)
            {
                return View("AddCourse", model);
            }

            //Create a new dto used to save the course
            var dto = new SaveCourseDto()
            {
                NumberOfYears = model.NumberOfYears,
                Title = model.Title
            };

            //Attempt to save the course. Check if this was successful
            var savedSuccessfully = await _service.SaveNewCourse(dto);

            //If the course already exists with the same title then return a model error stating that the course already exists.
            if (!savedSuccessfully) {
                ModelState.AddModelError("Title", "A course with this title already exists");
                return View("AddCourse", model);
            }

            //If the course saves successfully then redirect to the CourseList view method.
            return RedirectToAction("CourseList");
        }
    }
}

Administration.Site/Views/Course/AddCourse.cshtml
@using Administration.Site.Models;
@using ModuleChooser.Resources.Strings;

@{
    ViewBag.Title = Strings.AddCourse;
}

@section RenderCss {
    <link rel="stylesheet" href="~/Content/AddModule.css" type="text/css" />
    <link rel="stylesheet" href="~/Content/AddCourse.css" type="text/css" />
}

@model AddCourseModel

<h2>@Strings.AddCourse</h2>

<form id="form" action="@Url.Action("SaveNewCourse","Course")" method="post">
    <div id="information-div">
        <div>
            @Html.LabelFor(m => m.Title, new { @class = "information-label" })
            @Html.TextBoxFor(m => m.Title)
            @Html.ValidationMessageFor(m => m.Title)
        </div>
        <div>
            @Html.LabelFor(m => m.NumberOfYears, new { @class = "information-label" })
            @Html.DropDownListFor(m => m.NumberOfYears, Model.YearOptions)
            @Html.ValidationMessageFor(m => m.NumberOfYears)
        </div>
        <div>
            <input class="button" type="submit" value="Save" />
        </div>
    </div>
</form>

Administration.Site/Views/Course/AddModulesToCourse.cshtml
@using Administration.Site.Models;
@using ModuleChooser.Resources.Strings;

@{
    ViewBag.Title = Strings.AddModulesToCourse;
    ViewBag.Heading = Strings.AddModulesToCourse;

    //Get the number of years to use later
    var numberOfYears = Model.Select(m => m.YearOfStudy).Max();
}

@section RenderCss {
    <link rel="stylesheet" href="~/Content/AddModule.css" type="text/css" />
    <link rel="stylesheet" href="~/Content/AddModulesToCourse.css" type="text/css" />
}
@model List<AddModulesToCourseModel>

<button id="editButton" onclick="toggleNonClickable()">@Strings.ToggleEdit</button>

<div class="nonClickable" id="overlay">
    @for (int i = 1; i < numberOfYears + 1; i++)
    {
        <table id="table_id" class="table table-condensed table-striped table-hover">
            <thead>
                <tr>
                    <th>
                        @Strings.Title
                    </th>
                    <th>
                        @Strings.Credits
                    </th>
                    <th>
                        @Strings.ModuleCode
                    </th>
                    <th>
                        @Strings.Semester
                    </th>
                    <th>
                        @Strings.YearOfStudy
                    </th>
                    <th>
                        @Strings.Compulsory
                    </th>
                    <th>
                        @Strings.Option
                    </th>
                </tr>
            </thead>
            <tbody>
                @foreach (var item in Model.Where(m => m.YearOfStudy == i))
                {
                    <tr>
                        <td>
                            @Html.DisplayFor(modelItem => item.Title)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.Credits)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.ModuleCode)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.Semester)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.YearOfStudy)
                        </td>
                        <td>
                            @if (item.Compulsory)
                            {
                                @Html.CheckBox("compulsory_checkbox_for_" + @item.ModuleId, new { @onClick = "handleCompulsoryClick(this);", @checked = "true" })
                            }
                            else
                            {
                                @Html.CheckBox("compulsory_checkbox_for_" + @item.ModuleId, new { @onClick = "handleCompulsoryClick(this);" })
                            }
                        </td>
                        <td>
                            @if (item.Option)
                            {
                                @Html.CheckBox("option_checkbox_for_" + @item.ModuleId, new { @onClick = "handleOptionClick(this);", @checked = "true" })
                            }
                            else
                            {
                                @Html.CheckBox("option_checkbox_for_" + @item.ModuleId, new { @onClick = "handleOptionClick(this);" })
                            }
                        </td>
                    </tr>
                }
            </tbody>
        </table>
    }

    <div class="response-message" id="save-successful">@Strings.SavedSuccessfully</div>
    <div class="response-message" id="remove-successful">@Strings.RemovedSuccessfully</div>
</div>
<script type="text/javascript">

    function handleOptionClick(cb) {
        handleCheckboxClick(cb, false);
    }

    function handleCompulsoryClick(cb) {
        handleCheckboxClick(cb, true);
    }

    function handleCheckboxClick(cb, compulsory) {
        var splitcb = cb.id.split("_");
        if (compulsory) {
            //If compulsory clicked then check the option box to see if this is already selected
            splitcb[0] = "option";
        }
        else {
            //If option clicked then check the compulsory box to see if this is already selected
            splitcb[0] = "compulsory";
        }

        //Get the otherbox. eg. if option chosen then the otherbox will be the compulsory box
        var otherbox = "#".concat(splitcb.join("_"));

        //Get module id
        var moduleId = splitcb[3];

        //If the otherbox is already selected then deselect this box and call the changeCompulsoryStatus method.
        if ($(otherbox).is(':checked')) {
            changeCompulsoryStatus(moduleId);
            $(otherbox).removeAttr('checked');
        }
        else {
            //Otherwise save the module to course.Or remove if its been deselected
            if ($(cb).is(':checked')) {
                saveModuleToCourse(moduleId, compulsory)
            }
            else {
                removeModuleFromCourse(moduleId)
            }
        }
    }

    function saveModuleToCourse(moduleId, compulsory) {
        //Call the SaveModuleToCourse controller method , and show success message
        $.ajax({
            type: "POST",
            url: "@Url.Action("SaveModuleToCourse", "Course")",
            data: {
                moduleId: moduleId,
                courseId: "@ViewBag.CourseId",
                compulsory: compulsory

            },
            success: function () {
                messageShow($("#save-successful"));
            }
        });
    }

    function changeCompulsoryStatus(moduleId) {
        //Call the ChangeCompulsoryStatus controller method , and show success message
        $.ajax({
            type: "POST",
            url: "@Url.Action("ChangeCompulsoryStatus", "Course")",
            data: {
                moduleId: moduleId,
                courseId: "@ViewBag.CourseId"
            },
            success: function () {
                messageShow($("#save-successful"));
            }
        });
    }

    function removeModuleFromCourse(moduleId) {
        //Call the RemoveModuleFromCourse controller method , and show success message
        $.ajax({
            type: "POST",
            url: "@Url.Action("RemoveModuleFromCourse", "Course")",
            data: {
                moduleId: moduleId,
                courseId: "@ViewBag.CourseId"
            },
            success: function () {
                messageShow($("#remove-successful"));
            }
        });
    }

    function messageShow(item) {
        //Show message pop up
        item.slideDown("fast").delay(2000);
        item.slideUp("fast");
    }

    function toggleNonClickable() {
        //If the toggel edit button is clicked then toggle whether editing is allowed on the page.
        if ($('#overlay').hasClass('nonClickable')) {
            $('#overlay').removeClass('nonClickable');
        }
        else {
            $('#overlay').addClass('nonClickable');
        }
    }
</script>

Administration.Site/Views/Course/CourseList.cshtml
@using Administration.Site.Models
@using ModuleChooser.Resources.Strings;

@{
    ViewBag.Title = Strings.CourseList;
    ViewBag.Heading = Strings.CourseList;
}

@section RenderCss {
    <link rel="stylesheet" href="~/Content/CourseList.css" type="text/css" />
}

@model List<CourseModel>

<table id="table_id" class="table table-condensed table-striped table-hover">
    <thead>
        <tr>
            <th>
                @Strings.Title
            </th>
            <th>

            </th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Title)
                </td>
                <td>
                    @Html.ActionLink(Strings.ManageCourseModules, "AddModulesToCourse",
                      new { courseId = item.Id }, htmlAttributes: new
                      {
                          @class = "btn btn-default btn-sm add-modules-button"
                      })
                </td>
            </tr>
        }
    </tbody>
</table>